routes/admin.php
<?php

use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\Admin\AdminExercisePsychologicalTestController;
use App\Http\Controllers\Admin\AdminExerciseSkillTestController;
use App\Http\Controllers\Admin\AdminManagementController;
use App\Http\Controllers\Admin\AdminUserController;
use App\Http\Controllers\Admin\AdminUserDocumentController;
use App\Http\Controllers\Admin\AdminUserEducationController;
use App\Http\Controllers\Admin\AdminUserExperienceController;
use App\Http\Controllers\Admin\AdminUserStatusController;
use App\Http\Controllers\Admin\AdminVacancyDivisionController;
use App\Http\Controllers\Admin\AdminVacancyJobController;
use App\Http\Controllers\Admin\AdminVacancyLevelController;
use App\Http\Controllers\Admin\Auth\LoginController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->as('admin.')->group(function () {
    Route::get('login', [LoginController::class, 'getLogin'])->name('login');
    Route::post('login', [LoginController::class, 'postLogin'])->name('login.post');
    Route::get('logout', [LoginController::class, 'logout'])->name('logout');

    Route::middleware(['adminauth'])->group(function () {
        Route::get('/dashboard', [AdminDashboardController::class, 'index'])->name('dashboard');
        Route::get('/profile', [AdminDashboardController::class, 'profile'])->name('profile');
        Route::post('/profile/update', [AdminDashboardController::class, 'updateProfile'])->name('profile.update');
        Route::post('/profile/password/update', [AdminDashboardController::class, 'updateProfilePassword'])->name('profile.password.update');

        Route::prefix('management')->as('management.')->group(function () {
            Route::get('/', [AdminManagementController::class, 'index'])->name('index');
            Route::get('/create', [AdminManagementController::class, 'create'])->name('create');
            Route::post('/store', [AdminManagementController::class, 'store'])->name('store');
            Route::delete('/delete/{id}', [AdminManagementController::class, 'destroy'])->name('delete');
        });

        Route::prefix('user')->as('user.')->group(function () {
            Route::get('/', [AdminUserController::class, 'index'])->name('index');
            Route::get('/detail/{id}', [AdminUserController::class, 'show'])->name('show');
            Route::delete('/delete/{id}', [AdminUserController::class, 'deleteUser'])->name('delete');
            Route::get('/export', [AdminUserController::class, 'exportUser'])->name('export');

            Route::prefix('education')->as('education.')->group(function () {
                Route::get('/{user_id}', [AdminUserEducationController::class, 'index'])->name('index');
                Route::delete('/delete/{id}', [AdminUserEducationController::class, 'deleteEducation'])->name('delete');
            });

            Route::prefix('experience')->as('experience.')->group(function () {
                Route::get('/{user_id}', [AdminUserExperienceController::class, 'index'])->name('index');
                Route::delete('/delete/{id}', [AdminUserExperienceController::class, 'deleteExperience'])->name('delete');
            });

            Route::prefix('status')->as('status.')->group(function () {
                Route::get('/', [AdminUserStatusController::class, 'index'])->name('index');
                Route::get('/edit/{id}', [AdminUserStatusController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [AdminUserStatusController::class, 'update'])->name('update');
                Route::delete('/delete/{id}', [AdminUserStatusController::class, 'delete'])->name('delete');
                Route::get('/export', [AdminUserStatusController::class, 'exportUserStatus'])->name('export');
                Route::get('/view-test/{id}', [AdminUserStatusController::class, 'viewTest'])->name('view-test');
                Route::get('/view-data/{id}', [AdminUserStatusController::class, 'viewData'])->name('view-data');
            });

            Route::prefix('document')->as('document.')->group(function () {
                Route::get('/{user_id}', [AdminUserDocumentController::class, 'index'])->name('index');
                Route::delete('/delete/{id}', [AdminUserDocumentController::class, 'deleteDocument'])->name('delete');
            });
        });

        Route::prefix('vacancy')->as('vacancy.')->group(function () {
            Route::prefix('division')->as('division.')->group(function () {
                Route::get('/', [AdminVacancyDivisionController::class, 'index'])->name('index');
                Route::get('/create', [AdminVacancyDivisionController::class, 'create'])->name('create');
                Route::post('/store', [AdminVacancyDivisionController::class, 'store'])->name('store');
                Route::get('/edit/{id}', [AdminVacancyDivisionController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [AdminVacancyDivisionController::class, 'update'])->name('update');
                Route::delete('/delete/{id}', [AdminVacancyDivisionController::class, 'destroy'])->name('destroy');
            });

            Route::prefix('level')->as('level.')->group(function () {
                Route::get('/', [AdminVacancyLevelController::class, 'index'])->name('index');
                Route::get('/create', [AdminVacancyLevelController::class, 'create'])->name('create');
                Route::post('/store', [AdminVacancyLevelController::class, 'store'])->name('store');
                Route::get('/edit/{id}', [AdminVacancyLevelController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [AdminVacancyLevelController::class, 'update'])->name('update');
                Route::delete('/delete/{id}', [AdminVacancyLevelController::class, 'destroy'])->name('destroy');
            });

            Route::prefix('job')->as('job.')->group(function () {
                Route::get('/', [AdminVacancyJobController::class, 'index'])->name('index');
                Route::get('/detail/{id}', [AdminVacancyJobController::class, 'show'])->name('show');
                Route::get('/create', [AdminVacancyJobController::class, 'create'])->name('create');
                Route::post('/store', [AdminVacancyJobController::class, 'store'])->name('store');
                Route::get('/edit/{id}', [AdminVacancyJobController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [AdminVacancyJobController::class, 'update'])->name('update');
                Route::delete('/delete/{id}', [AdminVacancyJobController::class, 'destroy'])->name('destroy');
            });
        });

        Route::prefix('exercise')->as('exercise.')->group(function () {
            Route::prefix('psychological')->as('psychological.')->group(function () {
                Route::get('/', [AdminExercisePsychologicalTestController::class, 'index'])->name('index');
                Route::get('/detail/{id}', [AdminExercisePsychologicalTestController::class, 'show'])->name('show');
                Route::get('/create', [AdminExercisePsychologicalTestController::class, 'create'])->name('create');
                Route::post('/store', [AdminExercisePsychologicalTestController::class, 'store'])->name('store');
                Route::get('/edit/{id}', [AdminExercisePsychologicalTestController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [AdminExercisePsychologicalTestController::class, 'update'])->name('update');
                Route::delete('/delete/{id}', [AdminExercisePsychologicalTestController::class, 'destroy'])->name('destroy');
            });

            Route::prefix('skill')->as('skill.')->group(function () {
                Route::get('/', [AdminExerciseSkillTestController::class, 'index'])->name('index');
                Route::get('/detail/{id}', [AdminExerciseSkillTestController::class, 'show'])->name('show');
                Route::get('/create', [AdminExerciseSkillTestController::class, 'create'])->name('create');
                Route::post('/store', [AdminExerciseSkillTestController::class, 'store'])->name('store');
                Route::get('/edit/{id}', [AdminExerciseSkillTestController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [AdminExerciseSkillTestController::class, 'update'])->name('update');
                Route::delete('/delete/{id}', [AdminExerciseSkillTestController::class, 'destroy'])->name('destroy');
            });
        });
    });
});

routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\User\Auth\LoginController;
use App\Http\Controllers\User\Auth\RegisterController;
use App\Http\Controllers\User\UserApplicationTestController;
use App\Http\Controllers\User\UserDashboardController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Guest Route
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/job', [JobController::class, 'index'])->name('job');
Route::get('/job/detail/{id}', [JobController::class, 'show'])->name('job.detail');
Route::get('/job/filter/{id}', [JobController::class, 'filter'])->name('job.filter');
Route::get('/job/search', [JobController::class, 'search'])->name('job.search');
Route::get('/job/apply', [JobController::class, 'apply'])->name('job.apply');

Route::group(['middleware' => 'guest'], function () {
    Route::get('/login', [LoginController::class, 'index'])->name('login');
    Route::post('/login', [LoginController::class, 'authenticate'])->name('login.post');

    Route::get('/register', [RegisterController::class, 'index'])->name('register');
    Route::post('/register', [RegisterController::class, 'register'])->name('register.post');
});

Route::post('/logout', [LoginController::class, 'logout'])->name('logout');

// User Route
Route::group([
    'prefix'         => 'user',
    'as'            => 'user.',
    'middleware'    => 'auth'
], function () {
    Route::get('/dashboard', [UserDashboardController::class, 'index'])->name('dashboard');
    Route::get('/job', [UserDashboardController::class, 'listJob'])->name('job');
    Route::get('/job/detail/{id}', [UserDashboardController::class, 'showJob'])->name('job.detail');
    Route::get('/job/filter/{id}', [UserDashboardController::class, 'filterJob'])->name('job.filter');
    Route::get('/job/search', [UserDashboardController::class, 'searchJob'])->name('job.search');
    Route::get('/job/apply/{job_id}', [UserDashboardController::class, 'applyJob'])->name('job.apply');
    Route::get('/job/apply/store/{user_id}/{job_id}', [UserDashboardController::class, 'storeApplyJob'])->name('job.apply.store');
    Route::get('/profile/{id}', [UserDashboardController::class, 'profile'])->name('profile');
    Route::post('/profile/basic-info/update/{id}', [UserDashboardController::class, 'updateBasicInfo'])->name('profile.basic-info.update');

    Route::post('/profile/education/store/{id}', [UserDashboardController::class, 'storeEducation'])->name('profile.education.store');
    Route::get('/profile/education/edit/{id}', [UserDashboardController::class, 'editEducation'])->name('profile.education.edit');
    Route::post('/profile/education/update/{id}', [UserDashboardController::class, 'updateEducation'])->name('profile.education.update');
    Route::delete('/profile/education/delete/{id}', [UserDashboardController::class, 'deleteEducation'])->name('profile.education.delete');

    Route::post('/profile/experience/store/{id}', [UserDashboardController::class, 'storeExperience'])->name('profile.experience.store');
    Route::get('/profile/experience/edit/{id}', [UserDashboardController::class, 'editExperience'])->name('profile.experience.edit');
    Route::post('/profile/experience/update/{id}', [UserDashboardController::class, 'updateExperience'])->name('profile.experience.update');
    Route::delete('/profile/experience/delete/{id}', [UserDashboardController::class, 'deleteExperience'])->name('profile.experience.delete');

    Route::post('/profile/document/store/{id}', [UserDashboardController::class, 'storeDocument'])->name('profile.document.store');
    Route::get('/profile/document/edit/{id}', [UserDashboardController::class, 'editDocument'])->name('profile.document.edit');
    Route::post('/profile/document/update/{id}', [UserDashboardController::class, 'updateDocument'])->name('profile.document.update');
    Route::delete('/profile/document/delete/{id}', [UserDashboardController::class, 'deleteDocument'])->name('profile.document.delete');

    Route::get('/exam/psychological/{applicant_id}', [UserApplicationTestController::class, 'psychological'])->name('exam.psychological');
    Route::post('/exam/psychological/store', [UserApplicationTestController::class, 'submitPsychological'])->name('exam.psychological.store');
    Route::get('/exam/skill/{applicant_id}', [UserApplicationTestController::class, 'skill'])->name('exam.skill');
    Route::post('/exam/skill/store', [UserApplicationTestController::class, 'submitSkill'])->name('exam.skill.store');

    Route::get('/exam', [UserDashboardController::class, 'exam'])->name('exam');
});

resources/views/admin/vacancy/level/create.blade.php
@extends('admin.layouts.default')

@section('header')
<div class="header bg-primary pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
                        <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                            <li class="breadcrumb-item">
                                <a href="{{ route('admin.dashboard') }}"><i class="fas fa-home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{{ route('admin.dashboard') }}">Dashboard</a>
                            </li>
                            <li class="breadcrumb-item">Vacancy</li>
                            <li class="breadcrumb-item">
                                <a href="{{ route('admin.vacancy.level.index') }}">Level</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">Create</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('content')
<div class="row">
    <div class="col">
        <div class="card">
            <!-- Card header -->
            <div class="card-header border-1" style="background-color: #f6f9fc;">
                <div class="row">
                    <div class="col-6">
                        <h3 class="mb-0">Create Level</h3>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form method="post" action="{{ route('admin.vacancy.level.store') }}" autocomplete="off">
                    @csrf

                    <div class="pl-lg-4">
                        <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                            <label class="form-control-label" for="input-name">{{ __('Name') }} <span class="text-danger">*</span></label>
                            <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Level Name') }}" value="{{ old('name') }}" autofocus required>

                            @if ($errors->has('name'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="text-center">
                            <a href="{{ route('admin.vacancy.level.index') }}" class="btn btn-secondary">{{ __('Back') }}</a>
                            <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/vacancy/level/edit.blade.php
@extends('admin.layouts.default')

@section('header')
<div class="header bg-primary pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
                        <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                            <li class="breadcrumb-item">
                                <a href="{{ route('admin.dashboard') }}"><i class="fas fa-home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{{ route('admin.dashboard') }}">Dashboard</a>
                            </li>
                            <li class="breadcrumb-item">Vacancy</li>
                            <li class="breadcrumb-item">
                                <a href="{{ route('admin.vacancy.level.index') }}">Level</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">Edit</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('content')
<div class="row">
    <div class="col">
        <div class="card">
            <!-- Card header -->
            <div class="card-header border-1" style="background-color: #f6f9fc;">
                <div class="row">
                    <div class="col-6">
                        <h3 class="mb-0">Edit Level</h3>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form method="post" action="{{ route('admin.vacancy.level.update', $level->id) }}" autocomplete="off">
                    @csrf

                    <div class="pl-lg-4">
                        <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                            <label class="form-control-label" for="input-name">{{ __('Name') }} <span class="text-danger">*</span></label>
                            <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Level Name') }}" value="{{ old('name') ?? $level->name }}" autofocus required>

                            @if ($errors->has('name'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="text-center">
                            <a href="{{ route('admin.vacancy.level.index') }}" class="btn btn-secondary">{{ __('Back') }}</a>
                            <button type="submit" class="btn btn-primary">{{ __('Update') }}</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/vacancy/level/index.blade.php
@extends('admin.layouts.default')

@section('header')
<div class="header bg-primary pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
                        <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                            <li class="breadcrumb-item">
                                <a href="{{ route('admin.dashboard') }}"><i class="fas fa-home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{{ route('admin.dashboard') }}">Dashboard</a>
                            </li>
                            <li class="breadcrumb-item">Vacancy</li>
                            <li class="breadcrumb-item active" aria-current="page">Level</li>
                        </ol>
                    </nav>
                </div>
                @if (session('vacancyLevelMessage'))
                    <div class="col-lg-6 col-5">
                        <div class="alert alert-success alert-dismissible fade show p-2" role="alert">
                            <span class="alert-icon ml-3"><i class="ni ni-check-bold"></i></span> {{ session('vacancyLevelMessage') }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
</div>
@endsection

@section('content')
<div class="row">
    <div class="col">
        <div class="card">
            <!-- Card header -->
            <div class="card-header border-0">
                <div class="row">
                    <div class="col-6">
                        <h3 class="mb-0">Level List</h3>
                    </div>
                    <div class="col-6 text-right">
                        <a href="{{ route('admin.vacancy.level.create') }}" class="btn btn-primary btn-sm">
                            <i class="fas fa-plus"></i> Add Level
                        </a>
                    </div>
                </div>
            </div>
            <!-- Light table -->
            <div class="table-responsive">
                <table class="table align-items-center table-flush">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody class="list">
                        @forelse ($levels as $level)
                            <tr>
                                <td>{{ $level->name }}</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>
                                    <a href="{{ route('admin.vacancy.level.edit', $level->id) }}" class="btn btn-warning btn-sm">
                                        <i class="fas fa-edit"></i> Edit
                                    </a>
                                    <a href="javascript:;;" class="btn btn-danger btn-sm" onclick="deleteLevelModal({{ $level->id }})">
                                        <i class="fas fa-trash-alt"></i> Delete
                                    </a>
                                </td>
                            </tr>
                        @empty
                        <tr class="text-center">
                            <td colspan="4" class="text-muted">No data available</td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{{-- Modal Delete Level --}}
<div class="modal fade" id="deleteLevelModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
        <form id="deleteLevel" class="d-none" action="" method="post">
            @csrf
            @method('delete')

        </form>
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Delete Level</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            Are you sure you want to delete this data?
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            <button type="button" class="btn btn-danger" onclick="$('#deleteLevel').submit()">Yes</button>
        </div>
        </div>
    </div>
</div>
{{-- End Modal Delete Level --}}
@endsection

@section('scripts')
<script>
    function deleteLevelModal(id) {
        $('#deleteLevel').attr('action', '{{url('admin/vacancy/level/delete/')}}/'+id)
        $('#deleteLevelModal').modal('show')
    }
</script>
@endsection