routes/admin.php
<?php

use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\Admin\AdminExercisePsychologicalTestController;
use App\Http\Controllers\Admin\AdminExerciseSkillTestController;
use App\Http\Controllers\Admin\AdminManagementController;
use App\Http\Controllers\Admin\AdminUserController;
use App\Http\Controllers\Admin\AdminUserDocumentController;
use App\Http\Controllers\Admin\AdminUserEducationController;
use App\Http\Controllers\Admin\AdminUserExperienceController;
use App\Http\Controllers\Admin\AdminUserStatusController;
use App\Http\Controllers\Admin\AdminVacancyDivisionController;
use App\Http\Controllers\Admin\AdminVacancyJobController;
use App\Http\Controllers\Admin\AdminVacancyLevelController;
use App\Http\Controllers\Admin\Auth\LoginController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->as('admin.')->group(function () {
    Route::get('login', [LoginController::class, 'getLogin'])->name('login');
    Route::post('login', [LoginController::class, 'postLogin'])->name('login.post');
    Route::get('logout', [LoginController::class, 'logout'])->name('logout');

    Route::middleware(['adminauth'])->group(function () {
        Route::get('/dashboard', [AdminDashboardController::class, 'index'])->name('dashboard');
        Route::get('/profile', [AdminDashboardController::class, 'profile'])->name('profile');
        Route::post('/profile/update', [AdminDashboardController::class, 'updateProfile'])->name('profile.update');
        Route::post('/profile/password/update', [AdminDashboardController::class, 'updateProfilePassword'])->name('profile.password.update');

        Route::prefix('management')->as('management.')->group(function () {
            Route::get('/', [AdminManagementController::class, 'index'])->name('index');
            Route::get('/create', [AdminManagementController::class, 'create'])->name('create');
            Route::post('/store', [AdminManagementController::class, 'store'])->name('store');
            Route::delete('/delete/{id}', [AdminManagementController::class, 'destroy'])->name('delete');
        });

        Route::prefix('user')->as('user.')->group(function () {
            Route::get('/', [AdminUserController::class, 'index'])->name('index');
            Route::get('/detail/{id}', [AdminUserController::class, 'show'])->name('show');
            Route::delete('/delete/{id}', [AdminUserController::class, 'deleteUser'])->name('delete');
            Route::get('/export', [AdminUserController::class, 'exportUser'])->name('export');

            Route::prefix('education')->as('education.')->group(function () {
                Route::get('/{user_id}', [AdminUserEducationController::class, 'index'])->name('index');
                Route::delete('/delete/{id}', [AdminUserEducationController::class, 'deleteEducation'])->name('delete');
            });

            Route::prefix('experience')->as('experience.')->group(function () {
                Route::get('/{user_id}', [AdminUserExperienceController::class, 'index'])->name('index');
                Route::delete('/delete/{id}', [AdminUserExperienceController::class, 'deleteExperience'])->name('delete');
            });

            Route::prefix('status')->as('status.')->group(function () {
                Route::get('/', [AdminUserStatusController::class, 'index'])->name('index');
                Route::get('/edit/{id}', [AdminUserStatusController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [AdminUserStatusController::class, 'update'])->name('update');
                Route::delete('/delete/{id}', [AdminUserStatusController::class, 'delete'])->name('delete');
                Route::get('/export', [AdminUserStatusController::class, 'exportUserStatus'])->name('export');
                Route::get('/view-test/{id}', [AdminUserStatusController::class, 'viewTest'])->name('view-test');
                Route::get('/view-data/{id}', [AdminUserStatusController::class, 'viewData'])->name('view-data');
            });

            Route::prefix('document')->as('document.')->group(function () {
                Route::get('/{user_id}', [AdminUserDocumentController::class, 'index'])->name('index');
                Route::delete('/delete/{id}', [AdminUserDocumentController::class, 'deleteDocument'])->name('delete');
            });
        });

        Route::prefix('vacancy')->as('vacancy.')->group(function () {
            Route::prefix('division')->as('division.')->group(function () {
                Route::get('/', [AdminVacancyDivisionController::class, 'index'])->name('index');
                Route::get('/create', [AdminVacancyDivisionController::class, 'create'])->name('create');
                Route::post('/store', [AdminVacancyDivisionController::class, 'store'])->name('store');
                Route::get('/edit/{id}', [AdminVacancyDivisionController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [AdminVacancyDivisionController::class, 'update'])->name('update');
                Route::delete('/delete/{id}', [AdminVacancyDivisionController::class, 'destroy'])->name('destroy');
            });

            Route::prefix('level')->as('level.')->group(function () {
                Route::get('/', [AdminVacancyLevelController::class, 'index'])->name('index');
                Route::get('/create', [AdminVacancyLevelController::class, 'create'])->name('create');
                Route::post('/store', [AdminVacancyLevelController::class, 'store'])->name('store');
                Route::get('/edit/{id}', [AdminVacancyLevelController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [AdminVacancyLevelController::class, 'update'])->name('update');
                Route::delete('/delete/{id}', [AdminVacancyLevelController::class, 'destroy'])->name('destroy');
            });

            Route::prefix('job')->as('job.')->group(function () {
                Route::get('/', [AdminVacancyJobController::class, 'index'])->name('index');
                Route::get('/detail/{id}', [AdminVacancyJobController::class, 'show'])->name('show');
                Route::get('/create', [AdminVacancyJobController::class, 'create'])->name('create');
                Route::post('/store', [AdminVacancyJobController::class, 'store'])->name('store');
                Route::get('/edit/{id}', [AdminVacancyJobController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [AdminVacancyJobController::class, 'update'])->name('update');
                Route::delete('/delete/{id}', [AdminVacancyJobController::class, 'destroy'])->name('destroy');
            });
        });

        Route::prefix('exercise')->as('exercise.')->group(function () {
            Route::prefix('psychological')->as('psychological.')->group(function () {
                Route::get('/', [AdminExercisePsychologicalTestController::class, 'index'])->name('index');
                Route::get('/detail/{id}', [AdminExercisePsychologicalTestController::class, 'show'])->name('show');
                Route::get('/create', [AdminExercisePsychologicalTestController::class, 'create'])->name('create');
                Route::post('/store', [AdminExercisePsychologicalTestController::class, 'store'])->name('store');
                Route::get('/edit/{id}', [AdminExercisePsychologicalTestController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [AdminExercisePsychologicalTestController::class, 'update'])->name('update');
                Route::delete('/delete/{id}', [AdminExercisePsychologicalTestController::class, 'destroy'])->name('destroy');
            });

            Route::prefix('skill')->as('skill.')->group(function () {
                Route::get('/', [AdminExerciseSkillTestController::class, 'index'])->name('index');
                Route::get('/detail/{id}', [AdminExerciseSkillTestController::class, 'show'])->name('show');
                Route::get('/create', [AdminExerciseSkillTestController::class, 'create'])->name('create');
                Route::post('/store', [AdminExerciseSkillTestController::class, 'store'])->name('store');
                Route::get('/edit/{id}', [AdminExerciseSkillTestController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [AdminExerciseSkillTestController::class, 'update'])->name('update');
                Route::delete('/delete/{id}', [AdminExerciseSkillTestController::class, 'destroy'])->name('destroy');
            });
        });
    });
});

routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\User\Auth\LoginController;
use App\Http\Controllers\User\Auth\RegisterController;
use App\Http\Controllers\User\UserApplicationTestController;
use App\Http\Controllers\User\UserDashboardController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Guest Route
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/job', [JobController::class, 'index'])->name('job');
Route::get('/job/detail/{id}', [JobController::class, 'show'])->name('job.detail');
Route::get('/job/filter/{id}', [JobController::class, 'filter'])->name('job.filter');
Route::get('/job/search', [JobController::class, 'search'])->name('job.search');
Route::get('/job/apply', [JobController::class, 'apply'])->name('job.apply');

Route::group(['middleware' => 'guest'], function () {
    Route::get('/login', [LoginController::class, 'index'])->name('login');
    Route::post('/login', [LoginController::class, 'authenticate'])->name('login.post');

    Route::get('/register', [RegisterController::class, 'index'])->name('register');
    Route::post('/register', [RegisterController::class, 'register'])->name('register.post');
});

Route::post('/logout', [LoginController::class, 'logout'])->name('logout');

// User Route
Route::group([
    'prefix'         => 'user',
    'as'            => 'user.',
    'middleware'    => 'auth'
], function () {
    Route::get('/dashboard', [UserDashboardController::class, 'index'])->name('dashboard');
    Route::get('/job', [UserDashboardController::class, 'listJob'])->name('job');
    Route::get('/job/detail/{id}', [UserDashboardController::class, 'showJob'])->name('job.detail');
    Route::get('/job/filter/{id}', [UserDashboardController::class, 'filterJob'])->name('job.filter');
    Route::get('/job/search', [UserDashboardController::class, 'searchJob'])->name('job.search');
    Route::get('/job/apply/{job_id}', [UserDashboardController::class, 'applyJob'])->name('job.apply');
    Route::get('/job/apply/store/{user_id}/{job_id}', [UserDashboardController::class, 'storeApplyJob'])->name('job.apply.store');
    Route::get('/profile/{id}', [UserDashboardController::class, 'profile'])->name('profile');
    Route::post('/profile/basic-info/update/{id}', [UserDashboardController::class, 'updateBasicInfo'])->name('profile.basic-info.update');

    Route::post('/profile/education/store/{id}', [UserDashboardController::class, 'storeEducation'])->name('profile.education.store');
    Route::get('/profile/education/edit/{id}', [UserDashboardController::class, 'editEducation'])->name('profile.education.edit');
    Route::post('/profile/education/update/{id}', [UserDashboardController::class, 'updateEducation'])->name('profile.education.update');
    Route::delete('/profile/education/delete/{id}', [UserDashboardController::class, 'deleteEducation'])->name('profile.education.delete');

    Route::post('/profile/experience/store/{id}', [UserDashboardController::class, 'storeExperience'])->name('profile.experience.store');
    Route::get('/profile/experience/edit/{id}', [UserDashboardController::class, 'editExperience'])->name('profile.experience.edit');
    Route::post('/profile/experience/update/{id}', [UserDashboardController::class, 'updateExperience'])->name('profile.experience.update');
    Route::delete('/profile/experience/delete/{id}', [UserDashboardController::class, 'deleteExperience'])->name('profile.experience.delete');

    Route::post('/profile/document/store/{id}', [UserDashboardController::class, 'storeDocument'])->name('profile.document.store');
    Route::get('/profile/document/edit/{id}', [UserDashboardController::class, 'editDocument'])->name('profile.document.edit');
    Route::post('/profile/document/update/{id}', [UserDashboardController::class, 'updateDocument'])->name('profile.document.update');
    Route::delete('/profile/document/delete/{id}', [UserDashboardController::class, 'deleteDocument'])->name('profile.document.delete');

    Route::get('/exam/psychological/{applicant_id}', [UserApplicationTestController::class, 'psychological'])->name('exam.psychological');
    Route::post('/exam/psychological/store', [UserApplicationTestController::class, 'submitPsychological'])->name('exam.psychological.store');
    Route::get('/exam/skill/{applicant_id}', [UserApplicationTestController::class, 'skill'])->name('exam.skill');
    Route::post('/exam/skill/store', [UserApplicationTestController::class, 'submitSkill'])->name('exam.skill.store');

    Route::get('/exam', [UserDashboardController::class, 'exam'])->name('exam');
});

resources/views/admin/layouts/default.blade.php
<!--
=========================================================
* Argon Dashboard - v1.2.0
=========================================================
* Product Page: https://www.creative-tim.com/product/argon-dashboard


* Copyright  Creative Tim (http://www.creative-tim.com)
* Coded by www.creative-tim.com



=========================================================
* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
    <meta name="author" content="Creative Tim">
    <title>Administrator</title>
    <!-- Favicon -->
    <link rel="icon" href="{{ asset('assets/img/logo/logo.png') }}" type="image/png">
    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
    <!-- Icons -->
    <link rel="stylesheet" href="{{ asset('assets/vendor/nucleo/css/nucleo.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ asset('assets/vendor/@fortawesome/fontawesome-free/css/fontawesome.min.css') }}" type="text/css">
    <!-- Page plugins -->
    <!-- Argon CSS -->
    <link rel="stylesheet" href="{{ asset('assets/css/argon.css') }}" type="text/css">
    <!-- Font Awesome -->
    <link href="{{ asset('assets/vendor/@fortawesome/fontawesome-free/css/all.min.css') }}" rel="stylesheet">

    <style>
        .nav-item.nav-with-child > .nav-item-child
        {
            list-style: none;
            height: 0;
            min-height: 0px;
            overflow: hidden !important;
            padding: 0px 1.5rem;
            transition: all 0.5s ease-in-out;
            margin-left: 25px;
        }
        .nav-item.nav-with-child.nav-item-expanded > .nav-item-child
        {
            padding: 0.5rem 1.5rem;
            position: relative;
            height: auto;
            min-height: 50px;
            display: block;
            transition: all 0.5s ease-in-out;
        }

        a[data-toggle="collapse"] {
            position: relative;
        }
        .nav-dropdown-toggle::after {
            display: block;
            position: absolute;
            top: 50%;
            right: 20px;
            transform: translateY(-50%);
        }
    </style>
</head>

<body>
    <!-- Sidenav -->
    @include('admin.layouts.sidebar')

    <!-- Main content -->
    <div class="main-content" id="panel">
        <!-- Topnav -->
        @include('admin.layouts.top-navbar')

        <!-- Header -->
        @yield('header')

        <!-- Page content -->
        <div class="container-fluid mt--6">
            @yield('content')
        </div>

        <!-- Footer -->
        @include('admin.layouts.footer')
    </div>
    <!-- Argon Scripts -->
    <!-- Core -->
    <script src="{{ asset('assets/vendor/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/js-cookie/js.cookie.js') }}"></script>
    <script src="{{ asset('assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js') }}"></script>
    <!-- Optional JS -->
    <script src="{{ asset('assets/vendor/chart.js/dist/Chart.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/chart.js/dist/Chart.extension.js') }}"></script>

    @yield('scripts')

    <!-- Argon JS -->
    <script src="{{ asset('assets/js/argon.js?v=1.2.0') }}"></script>
    <script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
</body>

</html>

resources/views/admin/layouts/footer.blade.php
<div class="container">
    <footer class="footer">
        <div class="row align-items-end justify-content-lg-between">
            <div class="col-lg-6">
                <div class="copyright text-center text-lg-left text-muted">
                    &copy; {{ now()->year }} <span class="font-weight-bold ml-1">Intracks Market Services</span>
                </div>
            </div>
            <div class="col-lg-6 text-right">
                <small class="text-muted">
                    Made with <i class="fas fa-heart text-danger"></i>
                </small>
            </div>
        </div>
    </footer>
</div>

resources/views/admin/layouts/sidebar.blade.php
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">
        <!-- Brand -->
        <div class="sidenav-header  align-items-center">
            <a class="navbar-brand" href="javascript:void(0)">
                <h3>Intrack Market Services</h3>
            </a>
        </div>
        <div class="navbar-inner mt--3">
            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="sidenav-collapse-main">

                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link @if(Route::currentRouteName() === 'admin.dashboard') active @endif" href="{{ route('admin.dashboard') }}">
                            <i class="ni ni-planet text-primary"></i>
                            <span class="nav-link-text">Dashboard</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#applicant" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="vacancy">
                            <i class="ni ni-briefcase-24 text-primary"></i>
                            <span class="nav-link-text">Applicant</span>
                        </a>

                        <div class="collapse" id="applicant">
                            <ul class="nav nav-sm flex-column">
                                <li class="nav-item">
                                    <a class="nav-link {{ Request::is('admin/user*') ? 'active' : '' }}" href="{{ route('admin.user.index') }}">
                                        <i class="ni ni-circle-08 text-primary"></i>
                                        <span class="nav-link-text">Users</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link {{ Request::is('admin/user/status*') ? 'active' : '' }}" href="{{ route('admin.user.status.index') }}">
                                        <i class="ni ni-air-baloon text-primary"></i>
                                        <span class="nav-link-text">Status</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#vacancy" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="vacancy">
                            <i class="ni ni-briefcase-24 text-primary"></i>
                            <span class="nav-link-text">Vacancy</span>
                        </a>

                        <div class="collapse" id="vacancy">
                            <ul class="nav nav-sm flex-column">
                                <li class="nav-item">
                                    <a class="nav-link {{ Request::is('admin/vacancy/division*') ? 'active' : '' }}" href="{{ route('admin.vacancy.division.index') }}">
                                        <i class="ni ni-archive-2 text-primary"></i>
                                        <span class="nav-link-text">Divisions</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link {{ Request::is('admin/vacancy/level*') ? 'active' : '' }}" href="{{ route('admin.vacancy.level.index') }}">
                                        <i class="ni ni-badge text-primary"></i>
                                        <span class="nav-link-text">Levels</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link {{ Request::is('admin/vacancy/job*') ? 'active' : '' }}" href="{{ route('admin.vacancy.job.index') }}">
                                        <i class="ni ni-briefcase-24 text-primary"></i>
                                        <span class="nav-link-text">Jobs</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="#exercise" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="exercise">
                            <i class="ni ni-bullet-list-67 text-primary"></i>
                            <span class="nav-link-text">Exercise</span>
                        </a>

                        <div class="collapse" id="exercise">
                            <ul class="nav nav-sm flex-column">
                                <li class="nav-item">
                                    <a class="nav-link {{ Request::is('admin/exercise/psychological*') ? 'active' : '' }}" href="{{ route('admin.exercise.psychological.index') }}">
                                        <i class="ni ni-book-bookmark text-primary"></i>
                                        <span class="nav-link-text">Psychological Test</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link {{ Request::is('admin/exercise/skill*') ? 'active' : '' }}" href="{{ route('admin.exercise.skill.index') }}">
                                        <i class="ni ni-ruler-pencil text-primary"></i>
                                        <span class="nav-link-text">Skill Test</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>

                    @if(in_array(Auth::guard('admin')->user()->role, ['superadmin'] ))
                        <li class="nav-item">
                            <a class="nav-link @if(Route::currentRouteName() === 'admin.management*') active @endif" href="{{ route('admin.management.index') }}">
                                <i class="ni ni-single-02 text-primary"></i>
                                <span class="nav-link-text">Admin Management</span>
                            </a>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </div>
</nav>

resources/views/admin/layouts/top-navbar.blade.php
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav align-items-center ml-md-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        <div class="media align-items-center">
                            <div class="media-body  ml-2  d-none d-lg-block">
                                <span class="mb-0 text-sm  font-weight-bold">{{ auth()->guard('admin')->user()->name }}</span>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-menu  dropdown-menu-right ">
                        <a href="{{ route('admin.profile') }}" class="dropdown-item">
                            <i class="ni ni-single-02"></i>
                            <span>My profile</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="{{ route('admin.logout') }}" class="dropdown-item">
                            <i class="ni ni-user-run"></i>
                            <span>Logout</span>
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>