routes/admin.php
<?php

use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\Admin\AdminExercisePsychologicalTestController;
use App\Http\Controllers\Admin\AdminExerciseSkillTestController;
use App\Http\Controllers\Admin\AdminManagementController;
use App\Http\Controllers\Admin\AdminUserController;
use App\Http\Controllers\Admin\AdminUserDocumentController;
use App\Http\Controllers\Admin\AdminUserEducationController;
use App\Http\Controllers\Admin\AdminUserExperienceController;
use App\Http\Controllers\Admin\AdminUserStatusController;
use App\Http\Controllers\Admin\AdminVacancyDivisionController;
use App\Http\Controllers\Admin\AdminVacancyJobController;
use App\Http\Controllers\Admin\AdminVacancyLevelController;
use App\Http\Controllers\Admin\Auth\LoginController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->as('admin.')->group(function () {
    Route::get('login', [LoginController::class, 'getLogin'])->name('login');
    Route::post('login', [LoginController::class, 'postLogin'])->name('login.post');
    Route::get('logout', [LoginController::class, 'logout'])->name('logout');

    Route::middleware(['adminauth'])->group(function () {
        Route::get('/dashboard', [AdminDashboardController::class, 'index'])->name('dashboard');
        Route::get('/profile', [AdminDashboardController::class, 'profile'])->name('profile');
        Route::post('/profile/update', [AdminDashboardController::class, 'updateProfile'])->name('profile.update');
        Route::post('/profile/password/update', [AdminDashboardController::class, 'updateProfilePassword'])->name('profile.password.update');

        Route::prefix('management')->as('management.')->group(function () {
            Route::get('/', [AdminManagementController::class, 'index'])->name('index');
            Route::get('/create', [AdminManagementController::class, 'create'])->name('create');
            Route::post('/store', [AdminManagementController::class, 'store'])->name('store');
            Route::delete('/delete/{id}', [AdminManagementController::class, 'destroy'])->name('delete');
        });

        Route::prefix('user')->as('user.')->group(function () {
            Route::get('/', [AdminUserController::class, 'index'])->name('index');
            Route::get('/detail/{id}', [AdminUserController::class, 'show'])->name('show');
            Route::delete('/delete/{id}', [AdminUserController::class, 'deleteUser'])->name('delete');
            Route::get('/export', [AdminUserController::class, 'exportUser'])->name('export');

            Route::prefix('education')->as('education.')->group(function () {
                Route::get('/{user_id}', [AdminUserEducationController::class, 'index'])->name('index');
                Route::delete('/delete/{id}', [AdminUserEducationController::class, 'deleteEducation'])->name('delete');
            });

            Route::prefix('experience')->as('experience.')->group(function () {
                Route::get('/{user_id}', [AdminUserExperienceController::class, 'index'])->name('index');
                Route::delete('/delete/{id}', [AdminUserExperienceController::class, 'deleteExperience'])->name('delete');
            });

            Route::prefix('status')->as('status.')->group(function () {
                Route::get('/', [AdminUserStatusController::class, 'index'])->name('index');
                Route::get('/edit/{id}', [AdminUserStatusController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [AdminUserStatusController::class, 'update'])->name('update');
                Route::delete('/delete/{id}', [AdminUserStatusController::class, 'delete'])->name('delete');
                Route::get('/export', [AdminUserStatusController::class, 'exportUserStatus'])->name('export');
                Route::get('/view-test/{id}', [AdminUserStatusController::class, 'viewTest'])->name('view-test');
                Route::get('/view-data/{id}', [AdminUserStatusController::class, 'viewData'])->name('view-data');
            });

            Route::prefix('document')->as('document.')->group(function () {
                Route::get('/{user_id}', [AdminUserDocumentController::class, 'index'])->name('index');
                Route::delete('/delete/{id}', [AdminUserDocumentController::class, 'deleteDocument'])->name('delete');
            });
        });

        Route::prefix('vacancy')->as('vacancy.')->group(function () {
            Route::prefix('division')->as('division.')->group(function () {
                Route::get('/', [AdminVacancyDivisionController::class, 'index'])->name('index');
                Route::get('/create', [AdminVacancyDivisionController::class, 'create'])->name('create');
                Route::post('/store', [AdminVacancyDivisionController::class, 'store'])->name('store');
                Route::get('/edit/{id}', [AdminVacancyDivisionController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [AdminVacancyDivisionController::class, 'update'])->name('update');
                Route::delete('/delete/{id}', [AdminVacancyDivisionController::class, 'destroy'])->name('destroy');
            });

            Route::prefix('level')->as('level.')->group(function () {
                Route::get('/', [AdminVacancyLevelController::class, 'index'])->name('index');
                Route::get('/create', [AdminVacancyLevelController::class, 'create'])->name('create');
                Route::post('/store', [AdminVacancyLevelController::class, 'store'])->name('store');
                Route::get('/edit/{id}', [AdminVacancyLevelController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [AdminVacancyLevelController::class, 'update'])->name('update');
                Route::delete('/delete/{id}', [AdminVacancyLevelController::class, 'destroy'])->name('destroy');
            });

            Route::prefix('job')->as('job.')->group(function () {
                Route::get('/', [AdminVacancyJobController::class, 'index'])->name('index');
                Route::get('/detail/{id}', [AdminVacancyJobController::class, 'show'])->name('show');
                Route::get('/create', [AdminVacancyJobController::class, 'create'])->name('create');
                Route::post('/store', [AdminVacancyJobController::class, 'store'])->name('store');
                Route::get('/edit/{id}', [AdminVacancyJobController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [AdminVacancyJobController::class, 'update'])->name('update');
                Route::delete('/delete/{id}', [AdminVacancyJobController::class, 'destroy'])->name('destroy');
            });
        });

        Route::prefix('exercise')->as('exercise.')->group(function () {
            Route::prefix('psychological')->as('psychological.')->group(function () {
                Route::get('/', [AdminExercisePsychologicalTestController::class, 'index'])->name('index');
                Route::get('/detail/{id}', [AdminExercisePsychologicalTestController::class, 'show'])->name('show');
                Route::get('/create', [AdminExercisePsychologicalTestController::class, 'create'])->name('create');
                Route::post('/store', [AdminExercisePsychologicalTestController::class, 'store'])->name('store');
                Route::get('/edit/{id}', [AdminExercisePsychologicalTestController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [AdminExercisePsychologicalTestController::class, 'update'])->name('update');
                Route::delete('/delete/{id}', [AdminExercisePsychologicalTestController::class, 'destroy'])->name('destroy');
            });

            Route::prefix('skill')->as('skill.')->group(function () {
                Route::get('/', [AdminExerciseSkillTestController::class, 'index'])->name('index');
                Route::get('/detail/{id}', [AdminExerciseSkillTestController::class, 'show'])->name('show');
                Route::get('/create', [AdminExerciseSkillTestController::class, 'create'])->name('create');
                Route::post('/store', [AdminExerciseSkillTestController::class, 'store'])->name('store');
                Route::get('/edit/{id}', [AdminExerciseSkillTestController::class, 'edit'])->name('edit');
                Route::post('/update/{id}', [AdminExerciseSkillTestController::class, 'update'])->name('update');
                Route::delete('/delete/{id}', [AdminExerciseSkillTestController::class, 'destroy'])->name('destroy');
            });
        });
    });
});

routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\User\Auth\LoginController;
use App\Http\Controllers\User\Auth\RegisterController;
use App\Http\Controllers\User\UserApplicationTestController;
use App\Http\Controllers\User\UserDashboardController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Guest Route
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/job', [JobController::class, 'index'])->name('job');
Route::get('/job/detail/{id}', [JobController::class, 'show'])->name('job.detail');
Route::get('/job/filter/{id}', [JobController::class, 'filter'])->name('job.filter');
Route::get('/job/search', [JobController::class, 'search'])->name('job.search');
Route::get('/job/apply', [JobController::class, 'apply'])->name('job.apply');

Route::group(['middleware' => 'guest'], function () {
    Route::get('/login', [LoginController::class, 'index'])->name('login');
    Route::post('/login', [LoginController::class, 'authenticate'])->name('login.post');

    Route::get('/register', [RegisterController::class, 'index'])->name('register');
    Route::post('/register', [RegisterController::class, 'register'])->name('register.post');
});

Route::post('/logout', [LoginController::class, 'logout'])->name('logout');

// User Route
Route::group([
    'prefix'         => 'user',
    'as'            => 'user.',
    'middleware'    => 'auth'
], function () {
    Route::get('/dashboard', [UserDashboardController::class, 'index'])->name('dashboard');
    Route::get('/job', [UserDashboardController::class, 'listJob'])->name('job');
    Route::get('/job/detail/{id}', [UserDashboardController::class, 'showJob'])->name('job.detail');
    Route::get('/job/filter/{id}', [UserDashboardController::class, 'filterJob'])->name('job.filter');
    Route::get('/job/search', [UserDashboardController::class, 'searchJob'])->name('job.search');
    Route::get('/job/apply/{job_id}', [UserDashboardController::class, 'applyJob'])->name('job.apply');
    Route::get('/job/apply/store/{user_id}/{job_id}', [UserDashboardController::class, 'storeApplyJob'])->name('job.apply.store');
    Route::get('/profile/{id}', [UserDashboardController::class, 'profile'])->name('profile');
    Route::post('/profile/basic-info/update/{id}', [UserDashboardController::class, 'updateBasicInfo'])->name('profile.basic-info.update');

    Route::post('/profile/education/store/{id}', [UserDashboardController::class, 'storeEducation'])->name('profile.education.store');
    Route::get('/profile/education/edit/{id}', [UserDashboardController::class, 'editEducation'])->name('profile.education.edit');
    Route::post('/profile/education/update/{id}', [UserDashboardController::class, 'updateEducation'])->name('profile.education.update');
    Route::delete('/profile/education/delete/{id}', [UserDashboardController::class, 'deleteEducation'])->name('profile.education.delete');

    Route::post('/profile/experience/store/{id}', [UserDashboardController::class, 'storeExperience'])->name('profile.experience.store');
    Route::get('/profile/experience/edit/{id}', [UserDashboardController::class, 'editExperience'])->name('profile.experience.edit');
    Route::post('/profile/experience/update/{id}', [UserDashboardController::class, 'updateExperience'])->name('profile.experience.update');
    Route::delete('/profile/experience/delete/{id}', [UserDashboardController::class, 'deleteExperience'])->name('profile.experience.delete');

    Route::post('/profile/document/store/{id}', [UserDashboardController::class, 'storeDocument'])->name('profile.document.store');
    Route::get('/profile/document/edit/{id}', [UserDashboardController::class, 'editDocument'])->name('profile.document.edit');
    Route::post('/profile/document/update/{id}', [UserDashboardController::class, 'updateDocument'])->name('profile.document.update');
    Route::delete('/profile/document/delete/{id}', [UserDashboardController::class, 'deleteDocument'])->name('profile.document.delete');

    Route::get('/exam/psychological/{applicant_id}', [UserApplicationTestController::class, 'psychological'])->name('exam.psychological');
    Route::post('/exam/psychological/store', [UserApplicationTestController::class, 'submitPsychological'])->name('exam.psychological.store');
    Route::get('/exam/skill/{applicant_id}', [UserApplicationTestController::class, 'skill'])->name('exam.skill');
    Route::post('/exam/skill/store', [UserApplicationTestController::class, 'submitSkill'])->name('exam.skill.store');

    Route::get('/exam', [UserDashboardController::class, 'exam'])->name('exam');
});

app/Models/User.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'full_name',
        'birth_date',
        'gender',
        'address',
        'phone_number',
        'hobby',
        'image'
    ];

    protected $appends = [
        'user_age'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function educations()
    {
        return $this->hasMany(UserEducation::class);
    }

    public function experiences()
    {
        return $this->hasMany(UserExperience::class);
    }

    public function documents()
    {
        return $this->hasMany(UserDocument::class);
    }

    public function getUserAgeAttribute()
    {
        $birthDate = $this->birth_date;
        return Carbon::parse($birthDate)->diff(Carbon::now())->y;
    }
}

app/Http/Controllers/Admin/AdminUserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Exports\UsersExport;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\UserEducation;
use App\Models\UserExperience;
use Illuminate\Support\Facades\Response;
use Maatwebsite\Excel\Facades\Excel;

class AdminUserController extends Controller
{
    public function index()
    {
        $users = User::orderBy('created_at', 'desc')
            ->withCount('educations')
            ->withCount('experiences')
            ->withCount('documents')
            ->paginate(10);

        return view('admin.user.index', compact('users'));
    }

    public function show($id)
    {
        $user = User::find($id);

        return Response::json($user);
    }

    public function deleteUser($id)
    {
        // Delete relationship with user first
        $userEducation = UserEducation::getDataByUserId($id)->get();
        if (count($userEducation) > 0) {
            $userEducation->delete();
        }

        $userExperience = UserExperience::getDataByUserId($id)->get();
        if (count($userExperience) > 0) {
            $userExperience->delete();
        }

        User::find($id)->delete();

        return redirect()
            ->back()
            ->with('userDeleteSuccess', 'User deleted successfully');
    }

    public function exportUser()
    {
        return Excel::download(new UsersExport, 'users-applicant.xlsx');
    }
}

resources/views/admin/user/index.blade.php
@extends('admin.layouts.default')

@section('header')
<div class="header bg-primary pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
                        <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                            <li class="breadcrumb-item">
                                <a href="{{ route('admin.dashboard') }}"><i class="fas fa-home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{{ route('admin.dashboard') }}">Dashboard</a>
                            </li>
                            <li class="breadcrumb-item">Applicant</li>
                            <li class="breadcrumb-item active" aria-current="page">User</li>
                        </ol>
                    </nav>
                </div>
                @if (session('userDeleteSuccess'))
                    <div class="col-lg-6 col-5">
                        <div class="alert alert-success alert-dismissible fade show p-2" role="alert">
                            <span class="alert-icon ml-3"><i class="ni ni-check-bold"></i></span> {{ session('userDeleteSuccess') }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
</div>
@endsection

@section('content')
<div class="row">
    <div class="col">
        <div class="card">
            <!-- Card header -->
            <div class="card-header border-0">
                <div class="row">
                    <div class="col-6">
                        <h3 class="mb-0">Applicant List</h3>
                    </div>
                    <div class="col-6 text-right">
                        <a href="{{ route('admin.user.export') }}" class="btn btn-success btn-sm">
                            <i class="fas fa-file-export"></i> Export Applicant
                        </a>
                    </div>
                </div>
            </div>
            <!-- Light table -->
            <div class="table-responsive">
                <table class="table align-items-center table-flush">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Education</th>
                            <th scope="col">Experience</th>
                            <th scope="col">Document</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody class="list">
                        @forelse ($users as $user)
                            <tr>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                                <td>
                                    <a href="{{ route('admin.user.education.index', $user->id) }}" class="btn btn-primary btn-sm">
                                        <span>Educations</span>
                                        <span class="badge badge-primary">{{ $user->educations_count }}</span>
                                    </a>
                                </td>
                                <td>
                                    <a href="{{ route('admin.user.experience.index', $user->id) }}" class="btn btn-primary btn-sm">
                                        <span>Experiences</span>
                                        <span class="badge badge-primary">{{ $user->experiences_count }}</span>
                                    </a>
                                </td>
                                <td>
                                    <a href="{{ route('admin.user.document.index', $user->id) }}" class="btn btn-primary btn-sm">
                                        <span>Documents</span>
                                        <span class="badge badge-primary">{{ $user->documents_count }}</span>
                                    </a>
                                </td>
                                <td>
                                    <a href="javascript:void(0)" data-id="{{ $user->id }}" class="btn btn-info btn-sm showUserDetail">
                                        <i class="fas fa-eye"></i> View
                                    </a>
                                    <a href="javascript:;;" class="btn btn-danger btn-sm" onclick="deleteUserModal({{ $user->id }})">
                                        <i class="fas fa-trash-alt"></i> Delete
                                    </a>
                                </td>
                            </tr>
                        @empty
                        <tr class="text-center">
                            <td colspan="6" class="text-muted">No data available</td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
            <!-- Card footer -->
            <div class="card-footer py-4">
                {{ $users->links() }}
            </div>
        </div>
    </div>
</div>

{{-- Modal Show User Detail --}}
<div class="modal fade" id="showUserDetailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content bg-secondary">
            <div class="modal-header bg-default">
                <h1 class="modal-title text-secondary" id="exampleModalLabel">Detail User</h1>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span class="text-secondary" aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row mb-3">
                    <div class="col-12 text-center">
                        <img src="" alt="user profile image" id="image_profile" class="rounded" width="200" height="200">
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-8">
                        <label for="full_name" class="form-control-label">Full Name</label>
                        <input type="text" id="full_name" class="form-control form-control-alternative" readonly>
                    </div>
                    <div class="col-4">
                        <label for="email" class="form-control-label">Email</label>
                        <input type="text" id="email" class="form-control form-control-alternative" readonly>
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-6">
                        <label for="name" class="form-control-label">Name</label>
                        <input type="text" id="name" class="form-control form-control-alternative" readonly>
                    </div>
                    <div class="col-6">
                        <label for="phone_number" class="form-control-label">Phone Number</label>
                        <input type="text" id="phone_number" class="form-control form-control-alternative" readonly>
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-12">
                        <label for="address" class="form-control-label">Address</label>
                        <textarea name="address" id="address" cols="30" rows="3" class="form-control form-control-alternative" readonly></textarea>
                    </div>
                </div>

                <div class="row">
                    <div class="col-4">
                        <label for="gender" class="form-control-label">Gender</label>
                        <input type="text" id="gender" class="form-control form-control-alternative" readonly>
                    </div>
                    <div class="col-4">
                        <label for="birth_date" class="form-control-label">Birth Date</label>
                        <input type="text" id="birth_date" class="form-control form-control-alternative" readonly>
                    </div>
                    <div class="col-2">
                        <label for="age" class="form-control-label">Age</label>
                        <input type="text" id="age" class="form-control form-control-alternative" readonly>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{{-- End Modal Show User Detail --}}

{{-- Modal Delete User --}}
<div class="modal fade" id="deleteUserModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
        <form id="deleteUser" class="d-none" action="" method="post">
            @csrf
            @method('delete')

        </form>
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Delete User</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            Are you sure you want to delete this data?
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            <button type="button" class="btn btn-danger" onclick="$('#deleteUser').submit()">Yes</button>
        </div>
        </div>
    </div>
</div>
{{-- End Modal Delete User --}}
@endsection

@section('scripts')
<script>
    $(document).ready(function ($) {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $(".showUserDetail").click(function () {
            var id = $(this).data('id');
            var route = "user/detail/" + id;

            $.ajax({
                type: "GET",
                url: route,
                success: function (data) {
                    $('#full_name').val(data.full_name);
                    $('#name').val(data.name);
                    $('#email').val(data.email);
                    $('#birth_date').val(data.birth_date);
                    $('#age').val(data.user_age + ' Tahun');
                    $('#gender').val(data.gender);
                    $('#address').val(data.address);
                    $('#phone_number').val(data.phone_number);
                    if (data.image !== null) {
                        $('#image_profile').attr('src', "/image/user/profile/" + data.image);
                    }
                    $('#showUserDetailModal').modal('show');
                }
            });
        });
    })

    function deleteUserModal(id) {
        $('#deleteUser').attr('action', '{{url('admin/user/delete/')}}/'+id)
        $('#deleteUserModal').modal('show')
    }
</script>
@endsection